"""LLM-augmented training resumes — the "sharpen it" pass.

Our template generator (synth_resumes.py) is clean but too uniform, which is why
the model hits a suspicious 100% on its own data and only ~81% (masked) on an
independent set. This adds DIVERSITY: real-sounding, messy, varied resumes
generated by an LLM, so the classifier sees the kind of noise real resumes have.

Cost/safety: uses the project's own GROQ_API_KEY (root .env), free tier. Sends
NO user data — it only asks the model to invent fake resumes. Labeled by
construction (we asked for role X). PII-free by construction (fake people).
Fully optional: no key / any failure => writes nothing, the pipeline is unchanged.

Run:  python ml/llm_augment.py --per-role 10 --out ml/data/llm_aug.jsonl
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.utils.text import extract_skills  # noqa: E402
from ml.synth_resumes import TARGET_ROLES, ROLE_DOMAIN  # noqa: E402

GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = "llama-3.3-70b-versatile"


def _load_root_env() -> dict[str, str]:
    """Parse the git-ignored root .env (one level above backend/)."""
    path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), ".env")
    env: dict[str, str] = {}
    if os.path.exists(path):
        for line in open(path, encoding="utf-8"):
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def _groq_json(api_key: str, system: str, user: str, max_tokens: int = 4000) -> dict | None:
    body = json.dumps({
        "model": GROQ_MODEL,
        "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
        "temperature": 0.9,          # high — we WANT variety
        "max_tokens": max_tokens,
        "response_format": {"type": "json_object"},
    }).encode()
    req = urllib.request.Request(GROQ_URL, data=body, headers={
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
        # Groq sits behind Cloudflare, which blocks the default "Python-urllib"
        # UA with a 403 (error 1010). A normal UA is required, like the SDKs send.
        "User-Agent": "Lumina-ML/1.0",
    })
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())
        text = data["choices"][0]["message"]["content"]
        return json.loads(text)
    except Exception as exc:  # noqa: BLE001
        print(f"  ! groq call failed: {str(exc)[:160]}")
        return None


_SYSTEM = (
    "You generate realistic, DIVERSE synthetic resumes for training a role "
    "classifier. Vary seniority (intern to lead), length, formatting, phrasing, "
    "and industry. Include real-world MESSINESS: some career gaps, some overlapping "
    "skills across roles, inconsistent bullet styles, occasional typos. IMPORTANT: "
    "about half the resumes must NOT state the job title in the summary or headline "
    "(so the model learns from skills, not the label). Use ONLY fake names and fake "
    "contact info. Never include a real person."
)


def _prompt(role: str, n: int) -> str:
    return (
        f"Generate {n} DIFFERENT synthetic resumes for the role: {role} "
        f"(someone who specializes in {ROLE_DOMAIN.get(role, role)}). "
        f"Each resume is plain text with sections (summary, skills, experience, education). "
        f'Return strict JSON: {{"resumes": ["<full resume text>", ...]}} with exactly {n} strings.'
    )


def generate(per_role: int, batch: int = 5) -> list[dict]:
    env = _load_root_env()
    api_key = env.get("GROQ_API_KEY") or os.environ.get("GROQ_API_KEY", "")
    if not api_key:
        print("No GROQ_API_KEY found — skipping augmentation (pipeline unchanged).")
        return []

    rows: list[dict] = []
    for role in TARGET_ROLES:
        made = 0
        while made < per_role:
            n = min(batch, per_role - made)
            out = _groq_json(api_key, _SYSTEM, _prompt(role, n))
            texts = (out or {}).get("resumes", []) if isinstance(out, dict) else []
            for t in texts:
                if isinstance(t, str) and len(t) > 200:
                    rows.append({"text": t.strip(), "role": role, "skills": extract_skills(t)})
                    made += 1
            print(f"  {role:28} {made}/{per_role}")
            if not texts:
                break                       # give up on this role rather than loop forever
            time.sleep(2.0)                 # be gentle on the free-tier rate limit
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-role", type=int, default=10)
    ap.add_argument("--out", default="ml/data/llm_aug.jsonl")
    args = ap.parse_args()

    rows = generate(args.per_role)
    if not rows:
        return
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"\nWrote {len(rows)} LLM-augmented resumes -> {args.out}")


if __name__ == "__main__":
    main()
