"""Validate the role classifier against an INDEPENDENT dataset it never saw.

Our classifier was trained on our own template-generated resumes. This scores it
against AzharAli05/Resume-Screening-Dataset (MIT, LLM-generated by a *different*
process) — the honest generalization test. See ml/DATA_PROVENANCE.md.

Two numbers, same as training:
  - raw     : resume text as-is (role sometimes stated in the text)
  - masked  : each role's own name-words scrubbed -> can it infer from skills?

Only the roles that map cleanly to our 13-role taxonomy are scored; the external
set has no equivalent for Analytics Engineer / Power BI Developer / Backend /
Frontend, so those are out of scope for this check (an honest coverage gap).

Run:  python ml/validate_external.py
"""
from __future__ import annotations

import os
import re
import sys

import joblib
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, f1_score

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ml.pii import strip_pii  # noqa: E402

CSV = "ml/data/external/azharali_resume_screening.csv"
MODEL = "ml/models/role_clf.joblib"

# External label (case-normalized) -> our taxonomy. Only clean 1:1 maps; anything
# not here is dropped from the eval rather than force-fit (label noise is worse
# than a smaller, honest test set).
ROLE_MAP = {
    "data scientist": "Data Scientist",
    "data engineer": "Data Engineer",
    "data analyst": "Data Analyst",
    "devops engineer": "DevOps Engineer",
    "machine learning engineer": "Machine Learning Engineer",
    "cloud engineer": "Cloud Engineer",
    "full stack developer": "Full Stack Developer",
    "business analyst": "Business Analyst",
    "ai engineer": "AI Engineer",
}


def main() -> None:
    if not os.path.exists(MODEL):
        sys.exit("No model. Run: python ml/train_role_classifier.py")
    if not os.path.exists(CSV):
        sys.exit(f"No external data at {CSV}.")

    clf = joblib.load(MODEL)
    df = pd.read_csv(CSV)

    df["gold"] = df["Role"].astype(str).str.strip().str.lower().map(ROLE_MAP)
    df = df[df["gold"].notna()].copy()
    X = [strip_pii(str(t)) for t in df["Resume"]]
    y = df["gold"].tolist()

    print(f"Validating on {len(df)} external resumes across {df['gold'].nunique()} mapped roles")
    print(df["gold"].value_counts().to_string(), "\n")

    # raw
    pred = clf.predict(X)
    acc, f1m = accuracy_score(y, pred), f1_score(y, pred, average="macro")

    # masked: scrub every taxonomy role's words so the label can't be read off
    role_words = {w for r in set(ROLE_MAP.values()) for w in re.findall(r"[a-z]+", r.lower()) if len(w) > 2}
    mask_re = re.compile(r"\b(" + "|".join(sorted(role_words, key=len, reverse=True)) + r")\b", re.I)
    Xm = [mask_re.sub(" ", d) for d in X]
    pred_m = clf.predict(Xm)
    acc_m, f1_mm = accuracy_score(y, pred_m), f1_score(y, pred_m, average="macro")

    print("=== Classifier vs INDEPENDENT external set (never trained on) ===")
    print(f"accuracy (role words visible) : {acc:.3f}   macro-F1 {f1m:.3f}")
    print(f"accuracy (role words MASKED)  : {acc_m:.3f}   macro-F1 {f1_mm:.3f}   <- real signal\n")
    print(classification_report(y, pred, zero_division=0))

    # A few misclassifications for insight
    wrong = [(g, p, x) for g, p, x in zip(y, pred, X) if g != p]
    print(f"\n{len(wrong)} misclassified (raw). First 5:")
    for g, p, x in wrong[:5]:
        snippet = re.sub(r"\s+", " ", x)[:130]
        print(f"  gold={g:26} pred={p:26} | {snippet}…")


if __name__ == "__main__":
    main()
