# GENERATED FILE — DO NOT EDIT BY HAND.
# Source: shared/skills.json + shared/roles.json
# Regenerate: npm run gen:shared
"""Shared skill + role vocabulary, generated from the canonical JSON.

Single source of truth for BOTH stacks: the frontend ATS scorer and this
backend's job matcher must recognize exactly the same skills, or a resume gets
scored on skills the job search can't see.
"""
from __future__ import annotations

#: skill name -> alias substrings (lowercased).
SKILLS: dict[str, list[str]] = {
    "A/B Testing": ["ab testing","experimentation"],
    "Agile": ["kanban","scrum"],
    "Amazon Bedrock": ["bedrock"],
    "Amazon EMR": ["emr"],
    "Amazon Redshift": ["redshift"],
    "Amazon S3": ["s3"],
    "Apache Airflow": ["airflow"],
    "Apache Kafka": ["kafka"],
    "Apache Spark": ["pyspark","spark"],
    "AWS": ["amazon web services"],
    "AWS Lambda": ["lambda functions"],
    "Azure": ["microsoft azure"],
    "Azure Data Factory": ["adf"],
    "Azure Synapse": ["synapse analytics"],
    "Bash": ["shell script","shell scripting"],
    "BigQuery": ["google bigquery"],
    "Business Intelligence": ["bi"],
    "C#": [".net","csharp"],
    "C++": ["cpp"],
    "Cassandra": [],
    "CI/CD": ["cicd","continuous deployment","continuous integration"],
    "Claude API": ["anthropic api"],
    "Cross-functional Collaboration": ["cross functional","cross-functional teams"],
    "Data Analysis": ["data analytics"],
    "Data Governance": ["data lineage","data quality"],
    "Data Modeling": ["data modelling","dimensional modeling","star schema"],
    "Data Warehousing": ["data warehouse","dwh"],
    "Databricks": [],
    "DAX": [],
    "dbt": ["data build tool"],
    "Deep Learning": ["neural networks"],
    "Django": [],
    "Docker": ["containerization","containers"],
    "DynamoDB": [],
    "Elasticsearch": ["elastic search"],
    "ETL": ["data pipeline","data pipelines","elt","etl pipelines"],
    "Excel": ["google sheets","microsoft excel","ms excel"],
    "FastAPI": [],
    "Financial Analysis": ["financial operations","order to cash","order-to-cash","otc"],
    "Flask": [],
    "GCP": ["google cloud","google cloud platform"],
    "Git": ["github","gitlab","version control"],
    "Go": ["golang"],
    "GraphQL": [],
    "Hadoop": ["hdfs","mapreduce"],
    "HTML/CSS": ["css","html"],
    "Informatica": ["informatica powercenter"],
    "Java": [],
    "JavaScript": ["ecmascript","js"],
    "Jenkins": [],
    "JIRA": ["jira"],
    "JSON": [],
    "KPI Reporting": ["dashboarding","dashboards","kpi","kpis","sla monitoring"],
    "Kubernetes": ["k8s"],
    "Linux": ["unix"],
    "LLM Integration": ["gen ai","genai","generative ai","large language models","llm"],
    "Looker": ["looker studio"],
    "Machine Learning": ["ml"],
    "Medallion Architecture": ["bronze silver gold"],
    "Mentoring": ["knowledge transfer","training"],
    "MLOps": ["ml ops"],
    "MongoDB": ["mongo"],
    "MySQL": [],
    "Next.js": ["nextjs"],
    "NLP": ["natural language processing"],
    "Node.js": ["node","node.js","nodejs"],
    "NumPy": [],
    "OpenAI API": ["chatgpt api","gpt api"],
    "Oracle Database": ["oracle db","oracle sql"],
    "Oracle Fusion": ["bicc","oracle bicc","oracle fusion"],
    "Oracle ODI": ["odi","oracle data integrator"],
    "Pandas": [],
    "Performance Tuning": ["optimization","query optimization"],
    "PL/SQL": ["plsql"],
    "PostgreSQL": ["postgres"],
    "Power BI": ["power-bi","powerbi"],
    "Process Automation": ["automation","workflow automation"],
    "Project Management": ["program management"],
    "Prompt Engineering": [],
    "Python": [],
    "PyTorch": [],
    "R": ["r programming"],
    "RAG": ["retrieval augmented generation","retrieval-augmented generation"],
    "React": ["react.js","reactjs"],
    "Redis": [],
    "REST APIs": ["api development","rest api","restful"],
    "Rust": [],
    "Scala": [],
    "scikit-learn": ["sklearn"],
    "ServiceNow": [],
    "Snowflake": [],
    "SQL": ["mysql queries","pl/sql","t-sql"],
    "SQL Server": ["microsoft sql server","mssql"],
    "SSIS": ["sql server integration services"],
    "Stakeholder Management": ["stakeholder collaboration","stakeholder communication"],
    "Statistical Analysis": ["statistical modeling","statistics"],
    "Streaming": ["real time data","real-time data","stream processing"],
    "Tableau": [],
    "Tailwind CSS": ["tailwindcss"],
    "Technical Documentation": ["documentation","sops","tdd documents"],
    "TensorFlow": [],
    "Terraform": ["iac","infrastructure as code"],
    "Time Series Analysis": ["forecasting","time series"],
    "TypeScript": ["ts"],
    "XML Parsing": ["xml"],
}

#: skill name -> (category, difficulty). Not used for matching; kept so the
#: backend can reason about skill families without a second source of truth.
SKILL_META: dict[str, tuple[str, str]] = {
    "A/B Testing": ("analytics", "easy"),
    "Agile": ("soft", "easy"),
    "Amazon Bedrock": ("cloud", "easy"),
    "Amazon EMR": ("cloud", "moderate"),
    "Amazon Redshift": ("cloud", "moderate"),
    "Amazon S3": ("cloud", "easy"),
    "Apache Airflow": ("data", "moderate"),
    "Apache Kafka": ("data", "hard"),
    "Apache Spark": ("data", "hard"),
    "AWS": ("cloud", "moderate"),
    "AWS Lambda": ("cloud", "easy"),
    "Azure": ("cloud", "moderate"),
    "Azure Data Factory": ("cloud", "moderate"),
    "Azure Synapse": ("cloud", "moderate"),
    "Bash": ("language", "easy"),
    "BigQuery": ("cloud", "moderate"),
    "Business Intelligence": ("analytics", "moderate"),
    "C#": ("language", "moderate"),
    "C++": ("language", "hard"),
    "Cassandra": ("database", "hard"),
    "CI/CD": ("devops", "moderate"),
    "Claude API": ("ai", "easy"),
    "Cross-functional Collaboration": ("soft", "easy"),
    "Data Analysis": ("analytics", "easy"),
    "Data Governance": ("data", "moderate"),
    "Data Modeling": ("data", "moderate"),
    "Data Warehousing": ("data", "moderate"),
    "Databricks": ("data", "moderate"),
    "DAX": ("analytics", "moderate"),
    "dbt": ("data", "moderate"),
    "Deep Learning": ("ai", "hard"),
    "Django": ("web", "moderate"),
    "Docker": ("devops", "moderate"),
    "DynamoDB": ("database", "easy"),
    "Elasticsearch": ("database", "moderate"),
    "ETL": ("data", "moderate"),
    "Excel": ("analytics", "easy"),
    "FastAPI": ("web", "easy"),
    "Financial Analysis": ("analytics", "moderate"),
    "Flask": ("web", "easy"),
    "GCP": ("cloud", "moderate"),
    "Git": ("devops", "easy"),
    "Go": ("language", "moderate"),
    "GraphQL": ("web", "moderate"),
    "Hadoop": ("data", "hard"),
    "HTML/CSS": ("web", "easy"),
    "Informatica": ("data", "moderate"),
    "Java": ("language", "moderate"),
    "JavaScript": ("language", "moderate"),
    "Jenkins": ("devops", "moderate"),
    "JIRA": ("tool", "easy"),
    "JSON": ("tool", "easy"),
    "KPI Reporting": ("analytics", "easy"),
    "Kubernetes": ("devops", "hard"),
    "Linux": ("devops", "moderate"),
    "LLM Integration": ("ai", "moderate"),
    "Looker": ("analytics", "easy"),
    "Machine Learning": ("ai", "hard"),
    "Medallion Architecture": ("data", "easy"),
    "Mentoring": ("soft", "easy"),
    "MLOps": ("ai", "hard"),
    "MongoDB": ("database", "easy"),
    "MySQL": ("database", "easy"),
    "Next.js": ("web", "moderate"),
    "NLP": ("ai", "hard"),
    "Node.js": ("web", "moderate"),
    "NumPy": ("data", "easy"),
    "OpenAI API": ("ai", "easy"),
    "Oracle Database": ("database", "moderate"),
    "Oracle Fusion": ("data", "moderate"),
    "Oracle ODI": ("data", "moderate"),
    "Pandas": ("data", "easy"),
    "Performance Tuning": ("data", "moderate"),
    "PL/SQL": ("data", "moderate"),
    "PostgreSQL": ("database", "easy"),
    "Power BI": ("analytics", "easy"),
    "Process Automation": ("tool", "easy"),
    "Project Management": ("soft", "moderate"),
    "Prompt Engineering": ("ai", "easy"),
    "Python": ("language", "moderate"),
    "PyTorch": ("ai", "hard"),
    "R": ("language", "moderate"),
    "RAG": ("ai", "moderate"),
    "React": ("web", "moderate"),
    "Redis": ("database", "easy"),
    "REST APIs": ("web", "easy"),
    "Rust": ("language", "hard"),
    "Scala": ("language", "hard"),
    "scikit-learn": ("ai", "moderate"),
    "ServiceNow": ("tool", "easy"),
    "Snowflake": ("data", "moderate"),
    "SQL": ("language", "easy"),
    "SQL Server": ("database", "easy"),
    "SSIS": ("data", "moderate"),
    "Stakeholder Management": ("soft", "easy"),
    "Statistical Analysis": ("analytics", "moderate"),
    "Streaming": ("data", "hard"),
    "Tableau": ("analytics", "easy"),
    "Tailwind CSS": ("web", "easy"),
    "Technical Documentation": ("soft", "easy"),
    "TensorFlow": ("ai", "hard"),
    "Terraform": ("devops", "moderate"),
    "Time Series Analysis": ("analytics", "moderate"),
    "TypeScript": ("language", "moderate"),
    "XML Parsing": ("tool", "easy"),
}

#: role -> {skill: weight}. Drives resume-aware query planning.
ROLE_TRIGGERS: dict[str, dict[str, float]] = {
    "Data Engineer": {
        "ETL": 3,
        "Apache Spark": 3,
        "Apache Airflow": 3,
        "Apache Kafka": 2.5,
        "Data Warehousing": 2.5,
        "dbt": 2.5,
        "Snowflake": 2,
        "Databricks": 2.5,
        "Python": 1.5,
        "SQL": 1.5,
        "Data Modeling": 2,
        "Streaming": 2,
        "Hadoop": 2,
    },
    "ETL Developer": {
        "ETL": 3.5,
        "SQL": 2,
        "Data Warehousing": 2.5,
        "Apache Airflow": 2,
        "Azure Data Factory": 2.5,
        "Data Modeling": 2,
    },
    "Analytics Engineer": {
        "dbt": 3.5,
        "SQL": 2.5,
        "Data Modeling": 2.5,
        "Snowflake": 2,
        "BigQuery": 2,
        "Data Warehousing": 2,
        "Python": 1,
    },
    "Data Analyst": {
        "SQL": 2.5,
        "Excel": 2,
        "Power BI": 2.5,
        "Tableau": 2.5,
        "Data Analysis": 3,
        "Statistical Analysis": 2,
        "KPI Reporting": 2.5,
        "Python": 1,
        "Pandas": 1.5,
    },
    "Power BI Developer": {
        "Power BI": 4,
        "DAX": 3.5,
        "SQL": 1.5,
        "Data Modeling": 1.5,
        "KPI Reporting": 2,
        "Business Intelligence": 2,
    },
    "BI Developer": {
        "Power BI": 3,
        "Tableau": 2.5,
        "Looker": 2.5,
        "Business Intelligence": 3.5,
        "SQL": 2,
        "Data Warehousing": 2,
        "DAX": 2,
        "KPI Reporting": 2,
    },
    "Business Intelligence Engineer": {
        "Business Intelligence": 3.5,
        "SQL": 2,
        "Data Warehousing": 2.5,
        "Power BI": 2,
        "Tableau": 2,
        "ETL": 2,
        "Data Modeling": 2,
    },
    "Reporting Analyst": {
        "KPI Reporting": 3.5,
        "Power BI": 2.5,
        "Excel": 2.5,
        "SQL": 2,
        "Tableau": 2,
        "DAX": 1.5,
    },
    "SQL Developer": {
        "SQL": 4,
        "SQL Server": 3,
        "PostgreSQL": 2,
        "MySQL": 2,
        "Data Modeling": 1.5,
        "ETL": 1.5,
    },
    "Database Administrator": {
        "SQL Server": 3,
        "PostgreSQL": 2.5,
        "MySQL": 2.5,
        "MongoDB": 2,
        "SQL": 2,
        "Linux": 1.5,
    },
    "Azure Data Engineer": {
        "Azure": 3.5,
        "Azure Data Factory": 3.5,
        "Databricks": 2.5,
        "ETL": 2,
        "SQL": 1.5,
        "Data Warehousing": 2,
    },
    "AWS Data Engineer": {
        "AWS": 3.5,
        "Amazon Redshift": 3,
        "Amazon S3": 2.5,
        "AWS Lambda": 2,
        "ETL": 2,
        "Apache Spark": 2,
    },
    "Databricks Engineer": {
        "Databricks": 4,
        "Apache Spark": 3,
        "Python": 1.5,
        "Azure": 1.5,
        "Streaming": 1.5,
    },
    "Data Scientist": {
        "Machine Learning": 3.5,
        "Statistical Analysis": 3,
        "Python": 2,
        "Pandas": 2,
        "scikit-learn": 2.5,
        "Deep Learning": 2,
        "NumPy": 1.5,
        "Time Series Analysis": 2,
    },
    "Machine Learning Engineer": {
        "Machine Learning": 3.5,
        "PyTorch": 3,
        "TensorFlow": 3,
        "MLOps": 3,
        "Deep Learning": 2.5,
        "Python": 2,
        "Kubernetes": 1.5,
    },
    "AI Engineer": {
        "LLM Integration": 4,
        "RAG": 3.5,
        "Prompt Engineering": 3,
        "Machine Learning": 2,
        "Python": 2,
        "NLP": 2.5,
    },
    "Software Engineer": {
        "Python": 2,
        "Java": 2,
        "JavaScript": 2,
        "TypeScript": 2,
        "Go": 2,
        "REST APIs": 2,
        "Git": 1,
        "C++": 2,
        "C#": 2,
    },
    "Backend Developer": {
        "REST APIs": 3,
        "Node.js": 2.5,
        "Django": 2.5,
        "FastAPI": 2.5,
        "Flask": 2,
        "PostgreSQL": 2,
        "Java": 2,
        "Go": 2,
        "GraphQL": 2,
    },
    "Frontend Developer": {
        "React": 3.5,
        "Next.js": 3,
        "TypeScript": 2.5,
        "JavaScript": 2.5,
        "GraphQL": 1.5,
    },
    "Full Stack Developer": {
        "React": 2.5,
        "Node.js": 2.5,
        "TypeScript": 2,
        "REST APIs": 2,
        "Next.js": 2,
        "PostgreSQL": 1.5,
        "MongoDB": 1.5,
    },
    "DevOps Engineer": {
        "Docker": 3,
        "Kubernetes": 3.5,
        "CI/CD": 3,
        "Terraform": 3,
        "Jenkins": 2.5,
        "Linux": 2,
        "AWS": 1.5,
        "Azure": 1.5,
        "GCP": 1.5,
    },
    "Cloud Engineer": {
        "AWS": 3,
        "Azure": 3,
        "GCP": 3,
        "Terraform": 2.5,
        "Kubernetes": 2,
        "Docker": 1.5,
        "Linux": 1.5,
    },
    "Data Architect": {
        "Data Modeling": 3.5,
        "Data Warehousing": 3,
        "ETL": 2,
        "Snowflake": 2,
        "SQL": 1.5,
        "Apache Kafka": 1.5,
    },
    "Oracle ODI Developer": {
        "Oracle ODI": 4,
        "Oracle Fusion": 2.5,
        "ETL": 2.5,
        "PL/SQL": 2,
        "SQL": 1.5,
    },
    "Business Analyst": {
        "Excel": 2.5,
        "SQL": 2,
        "Stakeholder Management": 3,
        "Business Intelligence": 2,
        "KPI Reporting": 2,
        "Data Analysis": 2,
    },
}

#: (role, needle) pairs searched verbatim in resume text, beyond the plain
#: lowercased role names.
TITLE_ALIASES: list[tuple[str, str]] = [
    ("Data Engineer", "data engineering"),
    ("Data Analyst", "data analytics"),
    ("BI Developer", "business intelligence"),
    ("Oracle ODI Developer", "oracle odi"),
    ("Oracle ODI Developer", "odi developer"),
]
